extends Node

# ! Comments prefixed with "!" mean they are extra info. Comments without them
# ! should be kept because they give your mod structure and make it easier to
# ! read by other modders
# ! Comments with "?" should be replaced by you with the appropriate information

# ! This template file is statically typed. You don't have to do that, but it can help avoid bugs
# ! You can learn more about static typing in the docs
# ! https://docs.godotengine.org/en/3.5/tutorials/scripting/gdscript/static_typing.html

# ? Brief overview of what your mod does...

const AUTHORNAME_MODNAME_DIR := "8bithero-FirstModTrial" # Name of the directory that this file is in
const AUTHORNAME_MODNAME_LOG_NAME := "8bithero-FirstModTrial" # Full ID of the mod (AuthorName-ModName)

var mod_dir_path := ""
var extensions_dir_path := ""
var translations_dir_path := ""


# ! your _ready func.
func _init() -> void:
	ModLoaderLog.info("Init", AUTHORNAME_MODNAME_LOG_NAME)
	mod_dir_path = ModLoaderMod.get_unpacked_dir().plus_file(AUTHORNAME_MODNAME_DIR)

	# Add extensions
	install_script_extensions()

	# Add translations
	add_translations()


func install_script_extensions() -> void:
	# ! any script extensions should go in this directory, and should follow the same directory structure as vanilla
	extensions_dir_path = mod_dir_path.plus_file("extensions")

	# ? Brief description/reason behind this edit of vanilla code...
#	ModLoaderMod.install_script_extension(extensions_dir_path.plus_file("main.gd"))
	#ModLoaderMod.install_script_extension(ext_dir + "entities/units/player/player.gd") # ! Note that this file does not exist in this example mod

	# ! Add extensions (longform version of the above)
	#ModLoaderMod.install_script_extension("res://mods-unpacked/AuthorName-ModName/extensions/main.gd")
	#ModLoaderMod.install_script_extension("res://mods-unpacked/AuthorName-ModName/extensions/entities/units/player/player.gd")
	ModLoaderMod.install_script_extension(extensions_dir_path.plus_file("weapons/weapon.gd"))
	ModLoaderMod.install_script_extension(extensions_dir_path.plus_file("singletons/player_run_data.gd"))

	


func add_translations() -> void:
	# ! Place all of your translation files into this directory
	translations_dir_path = mod_dir_path.plus_file("translations")

	# ! Load translations for your mod, if you need them.
	# ! Add translations by adding a CSV called "modname.csv" into the "translations" directory.
	# ! Godot will automatically generate a ".translation" file, eg "modname.en.translation".
	# ! Note that in this example, only the file called "modname.csv" is custom;
	# ! any other files in the "translations" directory were automatically generated by Godot
	ModLoaderMod.add_translation(translations_dir_path.plus_file("weapons.en.translation"))
	ModLoaderMod.add_translation(translations_dir_path.plus_file("effects.en.translation"))

func _ready() -> void:
	# Get the ContentLoader class
	var ContentLoader = get_node("/root/ModLoader/Darkly77-ContentLoader/ContentLoader")

	var content_dir = "res://mods-unpacked/8bithero-FirstModTrial/"
	var mod_log = "8bithero-FirstModTrial"

	# Add content. These .tres files are ContentData resources
	ContentLoader.load_data(content_dir + "firstmodtrial_contents.tres", mod_log)
	get_effect_behaviors()

func get_effect_behaviors() -> void:
	var enemy_effect_behaviors = []
	enemy_effect_behaviors.append(load("res://mods-unpacked/8bithero-FirstModTrial/effect_behaviors/enemies/freeze_invulnerable/freeze_invulnerable_enemy_behavior_data.tres"))
	enemy_effect_behaviors.append(load("res://mods-unpacked/8bithero-FirstModTrial/effect_behaviors/enemies/time_slow/time_slow_enemy_behavior_data.tres"))
	EffectBehaviorService.enemy_effect_behaviors.append_array(enemy_effect_behaviors)
#
#func get_consumables() -> void:
#	var consumables = []
#	consumables.append(load("res://mods-unpacked/8bithero-FirstModTrial/items/consumables/super_arm_stone/super_arm_stone_data.tres"))
#	ItemService.consumables.append_array(consumables)
